services:
  - type: web
    name: fastapipos
    runtime: python
    buildCommand: poetry install
    startCommand: poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: POETRY_VERSION
        value: 1.7.1